target 'AutoSportWorld' do
  use_frameworks!
  
  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'
  pod 'SkyFloatingLabelTextField', '~> 3.0'

pod 'FacebookCore'
pod 'FacebookLogin'

end
