target 'AutoSportWorld' do
  inhibit_all_warnings!
  use_frameworks!
    pod 'SkyFloatingLabelTextField', '~> 3.0.0'
    pod 'VK-ios-sdk'
    pod 'GoogleMaps', '~> 2.3.1'
    pod 'GooglePlaces', '~> 2.3.1'
    pod 'RealmSwift', '~> 2.9.0'
    pod 'Alamofire' 
    pod 'SwiftyJSON'
    pod 'Kingfisher'

    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FSCalendar'
    pod 'IQKeyboardManager'
    pod 'CryptoSwift'
    
    pod 'Fabric'
    pod 'Crashlytics'
end
