target 'AutoSportWorld' do
  use_frameworks!

    pod 'SkyFloatingLabelTextField', '~> 3.0.0'
    pod 'VK-ios-sdk'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'RealmSwift'
    pod 'Alamofire'
    pod 'SwiftyJSON'

    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FSCalendar'

end
